### ISSUE TITLE
WaitFor() holds mutex whilst waiting

### ISSUE THREAD

**Issue by abligh** [traetox/goaio#1]
If two AIO requests (`A` and `B`) are pending, then `WaitFor()` is called for `A`, and before that terminates `WaitFor()` is called for `B`, the `WaitFor()` request for `B` will not end until the `WaitFor()` request for `A` has ended. Also, and more seriously, during this period a new request cannot be submitted. This assumes I am reading the code right!

This is because inside `WaitFor()` it holds `a.mtx` even when waiting. I believe the mutex is only meant to protect the members of `AIO`, rather than be held whilst it's actually in the `syscall`. I suspect the correct behaviour is to drop the mutex immediately before the call to `wait` and retake it afterwards (so the `defer` still does its job).

**Comment by abligh** [comment]
`a.Wait()` has a similar problem in that whilst waiting it will prevent any subsequent `WaitFor()`.

**Comment by traetox** [comment]
you are absolutely correct, i got lazy with the mutexes, I will correct.

On Sat, Apr 23, 2016 at 5:44 AM, Alex Bligh <notifications@github.com>
wrote:

> a.Wait() has a similar problem in that whilst waiting it will prevent any
> subsequent WaitFor().
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/traetox/goaio/issues/1#issuecomment-213725921>
>



-- 
:ZZ

**Comment by traetox** [comment]
corrected in 9bacff6

Mutexes are a hell of alot more complex now, but it seemed to speed things up a bit too.
